FROM makeomatic/node:6.2.1-vips

ONBUILD WORKDIR /src

ONBUILD COPY package.json .
ONBUILD RUN \
  apk add libvips-dev --no-cache --update --repository https://cdn.matic.ninja/apk/community \
  && npm install --production \
  && npm dedupe \
  && apk del \
    g++ \
    make \
    libvips-dev \
  && chown node /src \
  && rm -rf \
    /tmp/* \
    /root/.node-gyp \
    /root/.npm

ONBUILD USER node
ONBUILD COPY . /src
