FROM makeomatic/node:10.11.0-chrome

ONBUILD WORKDIR /src
ONBUILD COPY package.json yarn.lock ./
ONBUILD RUN \
  # be able to handle git pulls from https
  apk --update --no-cache add git \
  && yarn --production --frozen-lockfile \
  # cleanup git
  && apk del git \
  && yarn cache clean \
  && rm -rf \
    /root/.npm \
    /root/.node-gyp \
    /tmp/*

ONBUILD COPY . /src
ONBUILD RUN chown -R node /src
ONBUILD USER node
