FROM makeomatic/node:6.7.0

ONBUILD WORKDIR /src
ONBUILD COPY package.json .
ONBUILD RUN \
  # be able to handle git pulls from https
  apk --update --no-cache add git \
  && npm install --production \
  && npm dedupe \
  # cleanup git
  && apk del git \
  && rm -rf \
    /root/.npm \
    /root/.node-gyp \
    /tmp/*

ONBUILD COPY . /src
ONBUILD RUN chown -R node /src
ONBUILD USER node
