FROM makeomatic/node:$VERSION

# to build native deps
RUN \
  apk --no-cache add \
    build-base \
    python \
    make \
    lz4-dev \
    musl-dev \
    cyrus-sasl-dev \
    openssl-dev \
    zlib-dev \
    bash

WORKDIR /src
