FROM makeomatic/node:$VERSION

# set flag to disable rebuilding librdkafka on node-rdkafka package build
ENV BUILD_LIBRDKAFKA=0

RUN \
  apk --no-cache add \
    librdkafka \
    librdkafka-dev \
    python3 \
    make \
    g++ \
  # cleanup
  && rm -rf \
    /tmp/* \
    /var/cache/apk/*.tar.gz

WORKDIR /src
