FROM makeomatic/node:9.11.2-vips

# to build native deps
RUN \
  apk --update add \
    fftw-dev \
    vips-dev \
    build-base \
    python \
    make \
    ca-certificates \
    openssl \
    make \
    g++ \
    linux-headers \
  && rm -rf \
    /etc/apk/cache/* \
    /var/cache/apk/*

WORKDIR /src
