FROM makeomatic/node:6.9.5-vips

ONBUILD WORKDIR /src

ONBUILD COPY package.json .
ONBUILD RUN \
  apk add --no-cache --virtual .flavorDeps \
    git \
    g++ \
    make \
    fftw-dev \
    vips-dev@testing \
  && npm install --production \
  && npm dedupe \
  && apk del .flavorDeps \
  && rm -rf \
    /tmp/* \
    /root/.node-gyp \
    /root/.npm

ONBUILD COPY . /src
ONBUILD RUN chown -R node /src
ONBUILD USER node
