FROM makeomatic/node:$VERSION-vips-tester

# Installs latest Chromium (76) package.
RUN \
    apk --no-cache upgrade && \
    apk --no-cache add \
      chromium@edge \
      nss@edge \
      font-noto@edge

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
