FROM makeomatic/node:8.1.3-tex

# to build native deps
RUN \
  apk add --update \
    texlive-dev \
    build-base \
    python \
    make \
    ca-certificates \
    openssl \
    make \
    g++ \
    linux-headers \
  && rm -rf \
    /etc/apk/cache/* \
    /var/cache/apk/*

WORKDIR /src
