FROM makeomatic/node:8.1.0-tex

ONBUILD WORKDIR /src

ONBUILD COPY package.json yarn.lock ./
ONBUILD RUN \
  apk add --no-cache --virtual .flavorDeps \
    git \
    g++ \
    make \
    texlive-dev \
  && yarn --production \
  && apk del .flavorDeps \
  && rm -rf \
    /tmp/* \
    /root/.node-gyp \
    /root/.npm

ONBUILD COPY . /src
ONBUILD RUN chown -R node /src
ONBUILD USER node
